// This file is auto-generated by @hey-api/openapi-ts

export type AuthenticatedUser = {
    access_token: string;
    token_type: string;
    user: UserPrivate;
};

export type Body_remove_attendee_events_admin__event_id__remove_attendee_post = {
    user_id: string;
};

export type CreateVotes = {
    projects: Array<(string)>;
    event: string;
};

export type EventCreate = {
    name: string;
    description?: string;
    phase?: string;
    demo_links_optional?: boolean;
    repo_validation?: string;
    demo_validation?: string;
    custom_validator?: (string | null);
    feature_flags_csv?: string;
};

/**
 * Extended event info — visible to owner and superadmins.
 */
export type EventPrivate = {
    id: string;
    name: string;
    slug: string;
    description: string;
    phase: string;
    demo_links_optional: boolean;
    require_ysws_pii: boolean;
    max_votes_per_user: number;
    repo_validation: string;
    demo_validation: string;
    owner_id: string;
    custom_validator: (string | null);
    feature_flags_csv: string;
    deleted_at?: (string | null);
};

/**
 * Public event info — visible to anyone.
 */
export type EventPublic = {
    id: string;
    name: string;
    slug: string;
    description: string;
    phase: string;
    demo_links_optional: boolean;
    require_ysws_pii: boolean;
    max_votes_per_user: number;
    repo_validation: string;
    demo_validation: string;
};

/**
 * Request body for updating an event (PATCH semantics — all fields optional).
 */
export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    phase?: (string | null);
    demo_links_optional?: (boolean | null);
    require_ysws_pii?: (boolean | null);
    repo_validation?: (string | null);
    demo_validation?: (string | null);
    custom_validator?: (string | null);
    feature_flags_csv?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Page_EventPrivate_ = {
    items: Array<EventPrivate>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type Page_UserSummary_ = {
    items: Array<UserSummary>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

/**
 * Request body for creating a project.
 */
export type ProjectCreate = {
    name: string;
    repo: string;
    image_url: string;
    demo?: string;
    description?: string;
    hours_spent?: number;
    event_id: string;
};

/**
 * Private project info - visible to owner and collaborators.
 */
export type ProjectPrivate = {
    id: string;
    name: string;
    repo: string;
    image_url: string;
    demo: string;
    description: string;
    points: number;
    owner_id: string;
    owner_display_name?: string;
    collaborator_display_names?: Array<(string)>;
    join_code: string;
    hours_spent: number;
    event_id: string;
    validation_status: string;
    validation_message: string;
};

/**
 * Public project info - visible to anyone.
 */
export type ProjectPublic = {
    id: string;
    name: string;
    repo: string;
    image_url: string;
    demo: string;
    description: string;
    points: number;
    owner_id: string;
    owner_display_name?: string;
    collaborator_display_names?: Array<(string)>;
};

/**
 * Request body for updating a project. All fields optional.
 */
export type ProjectUpdate = {
    name?: (string | null);
    repo?: (string | null);
    image_url?: (string | null);
    demo?: (string | null);
    description?: (string | null);
    hours_spent?: (number | null);
};

export type ReferralResponse = {
    id: string;
    content: string;
    user_id: string;
    event_id: string;
};

/**
 * EventUpdate extended with superadmin-only fields.
 */
export type SuperadminEventUpdate = {
    name?: (string | null);
    description?: (string | null);
    phase?: (string | null);
    demo_links_optional?: (boolean | null);
    require_ysws_pii?: (boolean | null);
    repo_validation?: (string | null);
    demo_validation?: (string | null);
    custom_validator?: (string | null);
    feature_flags_csv?: (string | null);
    owner_email?: (string | null);
};

/**
 * Request body for creating a test event.
 */
export type TestEventCreate = {
    name: string;
    description?: string;
};

export type UserAttendee = {
    id: string;
    email: string;
    display_name: string;
    first_name: string;
    last_name: string;
};

export type UserEvents = {
    attending_events: Array<EventPublic>;
};

export type UserExistsResponse = {
    exists: boolean;
};

export type UserLoginPayload = {
    email: string;
};

/**
 * Authenticated user's self-view — returned by /users/current and /verify.
 * Non-sensitive identity fields only. Address/DOB not included (see UserInternal).
 */
export type UserPrivate = {
    id: string;
    display_name: string;
    email: string;
    first_name: string;
    last_name: string;
    phone?: string;
    vote_ids?: Array<(string)>;
    has_ysws_pii?: boolean;
    is_superadmin?: boolean;
    is_admin?: boolean;
    admin_permissions?: Array<string>;
};

/**
 * Public user info — visible to anyone.
 */
export type UserPublic = {
    id: string;
    display_name: string;
};

/**
 * Request body for user signup.
 */
export type UserSignup = {
    display_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    street_1?: (string | null);
    street_2?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    dob?: (string | null);
    email: string;
    first_name: string;
};

export type UserSummary = {
    id: string;
    email: string;
    display_name: string;
    is_superadmin: boolean;
    is_admin: boolean;
    admin_permissions_csv: string;
};

/**
 * Request body for profile update. None fields are excluded from the update.
 */
export type UserUpdate = {
    display_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    street_1?: (string | null);
    street_2?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    dob?: (string | null);
    first_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Outcome of a single validation check.
 */
export type ValidationResult = {
    valid: boolean;
    message: string;
};

export type VoteResponse = {
    id: string;
    voter_id: string;
    project_id: string;
    event_id: string;
};

export type RequestLoginRequestLoginPostData = {
    body: UserLoginPayload;
    query: {
        redirect: string;
    };
};

export type RequestLoginRequestLoginPostResponse = (unknown);

export type RequestLoginRequestLoginPostError = (HTTPValidationError);

export type VerifyTokenVerifyGetData = {
    query: {
        token: string;
    };
};

export type VerifyTokenVerifyGetResponse = (AuthenticatedUser);

export type VerifyTokenVerifyGetError = (HTTPValidationError);

export type SsoLoginAuthSsoGetResponse = (unknown);

export type SsoLoginAuthSsoGetError = unknown;

export type SsoCallbackAuthSsoCallbackGetData = {
    query: {
        code: string;
        state: string;
    };
};

export type SsoCallbackAuthSsoCallbackGetResponse = (unknown);

export type SsoCallbackAuthSsoCallbackGetError = (HTTPValidationError);

export type ListOfficialEventsEventsOfficialGetResponse = (Array<EventPublic>);

export type ListOfficialEventsEventsOfficialGetError = unknown;

export type GetEventEndpointEventsEventIdGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventEndpointEventsEventIdGetResponse = (EventPublic);

export type GetEventEndpointEventsEventIdGetError = (HTTPValidationError);

export type GetAttendingEventsEventsGetResponse = (UserEvents);

export type GetAttendingEventsEventsGetError = unknown;

export type AttendEventEventsEventIdAttendPostData = {
    path: {
        event_id: string;
    };
};

export type AttendEventEventsEventIdAttendPostResponse = (unknown);

export type AttendEventEventsEventIdAttendPostError = (HTTPValidationError);

export type VoteEventsVotePostData = {
    body: CreateVotes;
};

export type VoteEventsVotePostResponse = (unknown);

export type VoteEventsVotePostError = (HTTPValidationError);

export type GetEventProjectsEventsEventIdProjectsGetData = {
    path: {
        event_id: string;
    };
    query: {
        /**
         * Sort by points if true
         */
        leaderboard: boolean;
    };
};

export type GetEventProjectsEventsEventIdProjectsGetResponse = (Array<ProjectPublic>);

export type GetEventProjectsEventsEventIdProjectsGetError = (HTTPValidationError);

export type GetAtIdEventsIdSlugGetData = {
    path: {
        slug: string;
    };
};

export type GetAtIdEventsIdSlugGetResponse = (string);

export type GetAtIdEventsIdSlugGetError = (HTTPValidationError);

export type CreateTestEventEventsTestCreatePostData = {
    body: TestEventCreate;
};

export type CreateTestEventEventsTestCreatePostResponse = (EventPublic);

export type CreateTestEventEventsTestCreatePostError = (HTTPValidationError);

export type CleanupTestDataEventsTestCleanupPostResponse = (unknown);

export type CleanupTestDataEventsTestCleanupPostError = unknown;

export type GetEventAdminEventsAdminEventIdGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventAdminEventsAdminEventIdGetResponse = (EventPrivate);

export type GetEventAdminEventsAdminEventIdGetError = (HTTPValidationError);

export type UpdateEventAdminEventsAdminEventIdPatchData = {
    body: EventUpdate;
    path: {
        event_id: string;
    };
};

export type UpdateEventAdminEventsAdminEventIdPatchResponse = (EventPrivate);

export type UpdateEventAdminEventsAdminEventIdPatchError = (HTTPValidationError);

export type GetEventAttendeesEventsAdminEventIdAttendeesGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventAttendeesEventsAdminEventIdAttendeesGetResponse = (Array<UserAttendee>);

export type GetEventAttendeesEventsAdminEventIdAttendeesGetError = (HTTPValidationError);

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostData = {
    body: Body_remove_attendee_events_admin__event_id__remove_attendee_post;
    path: {
        event_id: string;
    };
};

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostResponse = (unknown);

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostError = (HTTPValidationError);

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetResponse = (Array<ProjectPrivate>);

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetError = (HTTPValidationError);

export type GetEventVotesEventsAdminEventIdVotesGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventVotesEventsAdminEventIdVotesGetResponse = (Array<VoteResponse>);

export type GetEventVotesEventsAdminEventIdVotesGetError = (HTTPValidationError);

export type GetEventReferralsEventsAdminEventIdReferralsGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventReferralsEventsAdminEventIdReferralsGetResponse = (Array<ReferralResponse>);

export type GetEventReferralsEventsAdminEventIdReferralsGetError = (HTTPValidationError);

export type GetProjectsProjectsMineGetResponse = (Array<ProjectPrivate>);

export type GetProjectsProjectsMineGetError = unknown;

export type CreateProjectProjectsPostData = {
    body: ProjectCreate;
};

export type CreateProjectProjectsPostResponse = (unknown);

export type CreateProjectProjectsPostError = (HTTPValidationError);

export type JoinProjectProjectsJoinPostData = {
    query: {
        /**
         * Project join code
         */
        join_code: string;
    };
};

export type JoinProjectProjectsJoinPostResponse = (unknown);

export type JoinProjectProjectsJoinPostError = (HTTPValidationError);

export type UpdateProjectProjectsProjectIdPutData = {
    body: ProjectUpdate;
    path: {
        project_id: string;
    };
};

export type UpdateProjectProjectsProjectIdPutResponse = (unknown);

export type UpdateProjectProjectsProjectIdPutError = (HTTPValidationError);

export type DeleteProjectProjectsProjectIdDeleteData = {
    path: {
        project_id: string;
    };
};

export type DeleteProjectProjectsProjectIdDeleteResponse = (unknown);

export type DeleteProjectProjectsProjectIdDeleteError = (HTTPValidationError);

export type GetProjectEndpointProjectsProjectIdGetData = {
    path: {
        project_id: string;
    };
};

export type GetProjectEndpointProjectsProjectIdGetResponse = (ProjectPublic);

export type GetProjectEndpointProjectsProjectIdGetError = (HTTPValidationError);

export type ValidateProjectProjectsValidatePostData = {
    query: {
        /**
         * Project ID to validate
         */
        project_id: string;
    };
};

export type ValidateProjectProjectsValidatePostResponse = (ValidationResult);

export type ValidateProjectProjectsValidatePostError = (HTTPValidationError);

export type ListAllEventsSuperadminEventsGetData = {
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
    };
};

export type ListAllEventsSuperadminEventsGetResponse = (Page_EventPrivate_);

export type ListAllEventsSuperadminEventsGetError = (HTTPValidationError);

export type CreateEventSuperadminEventsPostData = {
    body: EventCreate;
};

export type CreateEventSuperadminEventsPostResponse = (EventPrivate);

export type CreateEventSuperadminEventsPostError = (HTTPValidationError);

export type SoftDeleteEventSuperadminEventsEventIdDeleteData = {
    path: {
        event_id: string;
    };
};

export type SoftDeleteEventSuperadminEventsEventIdDeleteResponse = (unknown);

export type SoftDeleteEventSuperadminEventsEventIdDeleteError = (HTTPValidationError);

export type UpdateEventSuperadminEventsEventIdPatchData = {
    body: SuperadminEventUpdate;
    path: {
        event_id: string;
    };
};

export type UpdateEventSuperadminEventsEventIdPatchResponse = (EventPrivate);

export type UpdateEventSuperadminEventsEventIdPatchError = (HTTPValidationError);

export type ListUsersSuperadminUsersGetData = {
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
    };
};

export type ListUsersSuperadminUsersGetResponse = (Page_UserSummary_);

export type ListUsersSuperadminUsersGetError = (HTTPValidationError);

export type UserExistsUsersExistsGetData = {
    query: {
        email: string;
    };
};

export type UserExistsUsersExistsGetResponse = (UserExistsResponse);

export type UserExistsUsersExistsGetError = (HTTPValidationError);

export type GetCurrentUserInfoUsersCurrentGetResponse = (UserPrivate);

export type GetCurrentUserInfoUsersCurrentGetError = unknown;

export type UpdateCurrentUserUsersCurrentPutData = {
    body: UserUpdate;
};

export type UpdateCurrentUserUsersCurrentPutResponse = (UserPrivate);

export type UpdateCurrentUserUsersCurrentPutError = (HTTPValidationError);

export type GetUserPublicUsersUserIdGetData = {
    path: {
        user_id: string;
    };
};

export type GetUserPublicUsersUserIdGetResponse = (UserPublic);

export type GetUserPublicUsersUserIdGetError = (HTTPValidationError);

export type CreateUserUsersPostData = {
    body: UserSignup;
};

export type CreateUserUsersPostResponse = (unknown);

export type CreateUserUsersPostError = (HTTPValidationError);
